documentation/urls.py
from django.urls import path
from documentation import views

urlpatterns = [
    path('', views.index, name='index'),
    path('nav_cms/', views.nav_cms, name='nav_cms'),
    path('users/', views.users, name='users'),
    path('profile/', views.profile, name='profile'),
    path('messages/', views.messages, name='messages'),
    path('business/', views.business, name='business'),
    path('social/', views.social, name='social'),
    path('nav_mod/', views.nav_mod, name='nav_mod'),
    path('password_page/', views.password_page, name='password_page'),
    path('schedule/', views.schedule, name='schedule'),
    path('image_docs/', views.image_docs, name='image_docs'),
    path('blog/', views.blog, name='blog'),
    path('job/', views.job, name='job'),
    path('event/', views.event, name='event'),
    path('landing/', views.landing, name='landing'),
    path('seo/', views.seo, name='seo'),
    path('analytics/', views.analytics, name='analytics'),
    path('security/', views.security, name='security'),
    path('technical/', views.technical, name='technical'),
]

core/models.py
from blocks import blocks
from django.db import models
from django.shortcuts import render
from django.contrib import messages
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from autoslug import AutoSlugField
from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.contrib.settings.models import BaseSetting
from wagtail.contrib.settings.registry import register_setting
from wagtailmetadata.models import MetadataPageMixin
from wagtailmenus.models import AbstractMainMenuItem
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.admin.edit_handlers import StreamFieldPanel, TabbedInterface, ObjectList, FieldPanel, MultiFieldPanel


# Home Page ----------------------------------------------------------------------------------------------------------->
class HomePage(MetadataPageMixin, Page):
    template = 'frontend/index.html'
    max_count = 1
    hero = StreamField([
        ('title', blocks.ParallaxTitle())
    ])
    content = StreamField([
        ('services', blocks.ServiceCards()),
        ('testimonials', blocks.TestimonialCards()),
        ('CTA', blocks.CTABlock()),
        ('map', blocks.MapBlock()),
        ('FAQ', blocks.CardsWithFAQ()),
        ('latest_blog', blocks.LatestBlogPosts())
    ])
    title_panels = Page.content_panels + [
        StreamFieldPanel('hero')
    ]
    content_panels = [
        StreamFieldPanel('content')
    ]
    edit_handler = TabbedInterface([
        ObjectList(title_panels, heading='Title & Header'),
        ObjectList(content_panels, heading='Page Content'),
        ObjectList(MetadataPageMixin.promote_panels, heading='SEO/Menu'),
        ObjectList(Page.settings_panels, heading='Page Settings', classname='settings')
    ])

    class Meta:
        verbose_name = 'Home Page'


# About Page ---------------------------------------------------------------------------------------------------------->
class AboutPage(MetadataPageMixin, Page):
    max_count = 1
    parent_page_types = ['core.HomePage']
    subpage_types = []
    template = 'frontend/generic.html'

    hero = StreamField([
        ('title', blocks.MissionStatementBlock())
    ])
    content = StreamField([
        ('doctor_spotlight', blocks.DoctorSpotlight()),
        ('testimonials', blocks.TestimonialIllustration()),
        ('cta', blocks.CTALogoBlock()),
        ('map', blocks.MapBlock())
    ])
    title_panels = Page.content_panels + [
        StreamFieldPanel('hero')
    ]
    content_panels = [
        StreamFieldPanel('content')
    ]
    edit_handler = TabbedInterface([
        ObjectList(title_panels, heading='Title & Header'),
        ObjectList(content_panels, heading='Page Content'),
        ObjectList(MetadataPageMixin.promote_panels, heading='SEO/Menu'),
        ObjectList(Page.settings_panels, heading='Page Settings', classname='settings')
    ])

    class Meta:
        verbose_name = 'About Page'


# Testimonial Page ---------------------------------------------------------------------------------------------------->
class TestimonialPage(MetadataPageMixin, Page):
    """ Testimonial page utilizes Dr.com JavaScript plugin """
    max_count = 1
    parent_page_types = ['core.HomePage']
    subpage_types = []
    template = 'frontend/testimonial-page.html'

    class Meta:
        verbose_name = 'Testimonial Page'


# Contact Page & Message Model ---------------------------------------------------------------------------------------->
class Message(models.Model):
    """ Messages sent from the frontend of the website """
    first_name = models.CharField(
        max_length=30,
        blank=False
    )
    last_name = models.CharField(
        max_length=30,
        blank=False
    )
    email = models.EmailField(
        max_length=50,
        blank=False
    )
    phone_number = models.CharField(
        max_length=12,
        blank=False
    )
    message = models.TextField(
        max_length=2000,
        blank=False
    )
    staff_notes = models.TextField(
        blank=True,
        null=True,
        help_text='Internal notes for staff communication'
    )
    slug = AutoSlugField(
        populate_from='email'
    )
    viewed = models.BooleanField(default=False)
    sent_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-sent_on']

    def __str__(self):
        return self.first_name + ' ' + str(self.last_name)


class ContactPage(MetadataPageMixin, Page):
    max_count = 1
    parent_page_types = ['core.HomePage']
    subpage_types = []
    subtitle = models.CharField(
        max_length=255,
        blank=False,
        default='We will get back to you as soon as possible!'
    )
    background_image = models.ForeignKey(
        'wagtailimages.image',
        on_delete=models.PROTECT,
        verbose_name='Background Image',
        related_name='background_image'
    )
    map_image = models.ForeignKey(
        'wagtailimages.image',
        on_delete=models.PROTECT,
        verbose_name='Map Image',
        related_name='contact_map_image',
    )
    content_panels = Page.content_panels + [
        FieldPanel('subtitle'),
        ImageChooserPanel('background_image'),
        ImageChooserPanel('map_image')
    ]
    edit_handler = TabbedInterface([
        ObjectList(content_panels, heading='Page Content'),
        ObjectList(MetadataPageMixin.promote_panels, heading='SEO/Menu'),
        ObjectList(Page.settings_panels, heading='Page Settings', classname='settings')
    ])

    def serve(self, request):
        from core.forms import MessageForm
        # Valid form submission
        if request.method == 'POST':
            form = MessageForm(request.POST or None)
            if form.is_valid():
                # Save to database
                data = form.cleaned_data
                Message.objects.create(**data)
                # Send email to staff
                html_email = render_to_string('emails/staff-message.html', {'data': data})
                text_email = strip_tags(html_email)
                email = EmailMultiAlternatives(
                    f'New Message from {data["first_name"]} {data["last_name"]}',
                    text_email,
                    'Restore Orthopedics & Sports Medicine <donotreply@restoreorthobiologic.com>',
                    ['admin@restoreorthobiologic.com'],
                )
                email.attach_alternative(html_email, 'text/html')
                email.fail_silently = True
                email.send()
                # Reload page on successful submission
                form = MessageForm()
                messages.success(request, 'Your message has been received!')
                return render(request, 'form-pages/contact.html', {'form': form, 'self': self})
            else:
                # Reload page with error message if invalid
                messages.error(request, 'There seems to have been an error, '
                                        'please correct any missing or invalid fields.')
                return render(request, 'form-pages/contact.html', {'form': form, 'self': self})
        else:
            form = MessageForm()
            context = {'form': form, 'self': self}
            return render(request, 'form-pages/contact.html', context)

    class Meta:
        verbose_name = 'Contact Page'


# Legal Pages --------------------------------------------------------------------------------------------------------->
class LegalPage(MetadataPageMixin, Page):
    max_count = 1
    parent_page_types = ['core.HomePage']
    subpage_types = ['core.LegalPost']
    template = 'frontend/generic.html'

    hero = StreamField([
        ('title', blocks.TitleBlock())
    ])
    content = StreamField([
        ('cards', blocks.IconCardWithLink()),
        ('help', blocks.HelpBlock())
    ])
    title_panels = Page.content_panels + [
        StreamFieldPanel('hero')
    ]
    content_panels = [
        StreamFieldPanel('content')
    ]
    edit_handler = TabbedInterface([
        ObjectList(title_panels, heading='Title & Header'),
        ObjectList(content_panels, heading='Page Content'),
        ObjectList(MetadataPageMixin.promote_panels, heading='SEO/Menu'),
        ObjectList(Page.settings_panels, heading='Page Settings', classname='settings')
    ])

    class Meta:
        verbose_name = 'Legal Home Page'


class LegalPost(MetadataPageMixin, Page):
    parent_page_types = ['core.LegalPage']
    subpage_types = []
    template = 'frontend/generic.html'

    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    title_panels = Page.content_panels
    content = StreamField([
        ('legal_article', blocks.LegalBlock()),
    ])
    content_panels = [
        StreamFieldPanel('content'),
    ]
    edit_handler = TabbedInterface([
        ObjectList(title_panels, heading='Title & Header'),
        ObjectList(content_panels, heading='Page Content'),
        ObjectList(MetadataPageMixin.promote_panels, heading='SEO/Menu'),
        ObjectList(Page.settings_panels, heading='Page Settings', classname='settings')
    ])

    class Meta:
        verbose_name = 'Legal Policy'


# Global Settings ----------------------------------------------------------------------------------------------------->
@register_setting(icon='fa-facebook')
class SocialMediaSettings(BaseSetting):
    facebook = models.URLField(
        blank=True,
        null=True,
        help_text="Facebook URL",
        default='https://www.facebook.com/RestoreOrthopedics/'
    )
    twitter = models.URLField(
        blank=True,
        null=True,
        help_text="Twitter URL",
        default='https://twitter.com/OrthoSonora'
    )
    instagram = models.URLField(
        blank=True,
        null=True,
        help_text="Instagram URL",
        default='https://www.instagram.com/restoreorthobiologic/'
    )

templates/form-pages/appointment-request.html
{% extends 'base.html' %}{% load static wagtailcore_tags wagtailimages_tags wagtailmetadata_tags %}{% block content %}
    <section class="jarallax position-relative bg-gradient" data-jarallax data-speed="0.25" style="height: 590px;">
        <span class="bg-overlay bg-gradient" style="opacity: .8;"></span>{% image self.background_image original format-png as background_image %}
        <div class="jarallax-img" style="background-image: url({{ background_image.url }});"></div>
        <div class="cs-shape cs-shape-bottom cs-shape-curve-side bg-body">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3000 250">
                <g><path fill="currentColor" d="M3000,0v250H0v-51c572.7,34.3,1125.3,34.3,1657.8,0C2190.3,164.8,2637.7,98.4,3000,0z"></path></g>
            </svg>
        </div>
    </section>
    <section class="container bg-overlay-content pt-7" style="margin-top: -590px;">
        <div class="row pt-md-4 pt-lg-5 mt-3">
            <div class="col-lg-4 col-md-5 offset-lg-1">
                <h1 class="text-light mb-3 pb-4 pt-sm-3">Request an Appointment</h1>
                <div class="d-flex mb-4"><i class="fe-map-pin h3 mb-2 text-light mt-1"></i>
                    <div class="pl-3">
                        <p class="text-light mb-2">{{ settings.core.BusinessSettings.street_address }},<br>{{ settings.core.BusinessSettings.city }}, {{ settings.core.BusinessSettings.state }} {{ settings.core.BusinessSettings.zip }}</p>
                        <a class="cs-fancy-link text-light font-size-sm" href="#map" data-scroll>See on the map</a>
                    </div>
                </div>
                <div class="d-flex mb-4"><i class="fe-mail h3 mb-2 text-light"></i>
                    <div class="pl-3">
                        <a class="d-inline-block text-light text-decoration-none mb-2" href="mailto:{{ settings.core.BusinessSettings.email }}">{{ settings.core.BusinessSettings.email }}</a>
                    </div>
                </div>
                <div class="d-flex mb-4"><i class="fe-phone h3 mb-2 text-light"></i>
                    <div class="pl-3">
                        <a class="d-inline-block text-light text-decoration-none mb-2" href="tel:{{ settings.core.BusinessSettings.phone }}">{{ settings.core.BusinessSettings.phone }}</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-md-7">
                <div class="card border-0 box-shadow-lg">
                    <div class="card-body py-5 px-3 px-sm-4">
                        <h2 class="h3 text-center">Request an Appointment</h2>
                        {% include 'partials/_alerts.html' %}
                        <form class="needs-validation pt-2 px-md-3" method="POST" novalidate>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_first_name">First Name<sup class="text-danger ml-1">*</sup></label> {{ form.first_name }}
                                    <div class="invalid-feedback">Please enter your first name.</div>
                                    {% for error in form.first_name.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_last_name">Last name<sup class="text-danger ml-1">*</sup></label> {{ form.last_name }}
                                    <div class="invalid-feedback">Please enter your last name.</div>
                                    {% for error in form.last_name.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_email">Email address<sup class="text-danger ml-1">*</sup></label>{{ form.email }}
                                    <div class="invalid-feedback">Please enter a valid email address.</div>
                                    {% for error in form.email.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_phone_number">Phone number<sup class="text-danger ml-1">*</sup></label>{{ form.phone_number }}
                                    <div class="invalid-feedback">Please enter your phone number.</div>
                                    {% for error in form.phone_number.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="id_ideal_day">Ideal day of week<sup class="text-danger ml-1">*</sup></label>{{ form.ideal_day }}
                                    <div class="invalid-feedback">Please make a selection.</div>
                                    {% for error in form.ideal_day.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="id_appointment_type">Appointment type<sup class="text-danger ml-1">*</sup></label>{{ form.appointment_type }}
                                    <div class="invalid-feedback">Please make a selection.</div>
                                    {% for error in form.appointment_type.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="cont-message">Message<sup class="text-danger ml-1">*</sup></label>
                                {{ form.message }}
                                <div class="invalid-feedback">Please write a message!</div>
                                {% for error in form.message.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                            </div>
                            <div class="text-center pt-2">
                                {% csrf_token %}
                                {{ form.captcha }}
                                <button class="btn btn-primary" type="submit">Send Message</button>
                                {% for error in form.captcha.errors %}<small class="text-danger form-text">{{ error|escape }}</small>{% endfor %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="container py-5 py-md-6 py-lg-7" id="location">
        <div class="row py-sm-3">
            <div class="col-md-7">
                <div class="cs-gallery" id="map">{% image self.map_image fill-703x450 format-png as map_image %}
                    <a class="cs-gallery-item cs-map-popup bg-position-center bg-no-repeat py-7 text-center border rounded-lg" href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3145.0021611401357!2d-120.34119544822403!3d37.9770788796236!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8090c528b63b1ba3%3A0xb75939887ae2279d!2sRestore%20Orthopedics%20and%20Sports%20Medicine%3A%20Ariana%20DeMers%2C%20D.O.!5e0!3m2!1sen!2sus!4v1594873054045!5m2!1sen!2sus" data-iframe="true" data-sub-html="&lt;h6 class=&quot;font-size-sm text-light&quot;&gt;{{ settings.core.BusinessSettings.name }}&lt;/h6&gt;" style="background-image: url({{ map_image.url }});"><span class="cs-gallery-caption"><i class="fe-maximize-2 font-size-xl mt-n1 mr-2"></i>Expand the map</span>
                        <div class="d-inline-block py-4 py-sm-7"><img width="48" src="{% static 'img/svg/marker.svg' %}" alt="Map marker"/></div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 offset-md-1 pt-4">
                <h2 class="h4 pb-3">Our Location</h2>
                <h3 class="h5">Address</h3>
                <ul class="list-unstyled font-size-sm mb-4 pb-2">
                    <li>{{ settings.core.BusinessSettings.street_address }}</li>
                    <li>{{ settings.core.BusinessSettings.city }}, {{ settings.core.BusinessSettings.state }} {{ settings.core.BusinessSettings.zip }}</li>
                </ul>
                <h2 class="h4 pb-2">Working hours</h2>
                <ul class="list-unstyled font-size-sm">
                    <li><span class="text-heading font-size-base mr-1">Sunday: </span><span class="text-danger">{{ settings.core.BusinessSettings.sunday_hours }}</span></li>
                    <li><span class="text-heading font-size-base mr-1">Monday: </span>{{ settings.core.BusinessSettings.monday_hours }}</li>
                    <li><span class="text-heading font-size-base mr-1">Tuesday: </span>{{ settings.core.BusinessSettings.tuesday_hours }}</li>
                    <li><span class="text-heading font-size-base mr-1">Wednesday: </span>{{ settings.core.BusinessSettings.wednesday_hours }}</li>
                    <li><span class="text-heading font-size-base mr-1">Thursday: </span>{{ settings.core.BusinessSettings.thursday_hours }}</li>
                    <li><span class="text-heading font-size-base mr-1">Friday: </span>{{ settings.core.BusinessSettings.friday_hours }}</li>
                    <li><span class="text-heading font-size-base mr-1">Saturday: </span><span class="text-danger">{{ settings.core.BusinessSettings.saturday_hours }}</span></li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}{% block extra_js %}
    <script src="{% static 'vendor/cleave.js/dist/cleave.min.js' %}"></script>
    <script src="{% static 'vendor/jarallax/dist/jarallax.min.js' %}"></script>
    <script src="{% static 'vendor/lightgallery.js/dist/js/lightgallery.min.js' %}"></script>
    <script>

    </script>
{% endblock %}

templates/form-pages/contact.html
{% extends 'base.html' %}{% load cache static wagtailcore_tags wagtailimages_tags wagtailmetadata_tags %}{% block content %}
    <section class="jarallax position-relative bg-gradient" data-jarallax data-speed="0.25" style="height: 590px;">
        <span class="bg-overlay bg-gradient" style="opacity: .8;"></span>{% image self.background_image max-1220x380 format-jpeg as background_image %}
        <div class="jarallax-img" style="background-image: url({{ background_image.url }});"></div>
        <div class="cs-shape cs-shape-bottom cs-shape-curve-side bg-body">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3000 250">
                <g>
                    <path fill="currentColor" d="M3000,0v250H0v-51c572.7,34.3,1125.3,34.3,1657.8,0C2190.3,164.8,2637.7,98.4,3000,0z"></path>
                </g>
            </svg>
        </div>
    </section>
    <section class="container bg-overlay-content pt-2 pt-md-7 pt-lg-7 pt-xl-7" style="margin-top: -590px;">{% cache 43200 contact_page_info %}
        <div class="row pt-md-4 pt-lg-5 mt-3">
            <div class="col-lg-4 col-md-5 offset-lg-1">
                <h1 class="text-light mb-3 pb-4 pt-sm-3">{{ self.title }}</h1>
                <div class="d-flex mb-4"><i class="fe-map-pin h3 mb-2 text-light mt-1"></i>
                    <div class="pl-3">
                        <p class="text-light mb-2">{{ settings.core.BusinessSettings.street_address }},<br>{{ settings.core.BusinessSettings.city }}, {{ settings.core.BusinessSettings.state }} {{ settings.core.BusinessSettings.zip }}
                        </p>
                        <a class="cs-fancy-link text-light font-size-sm" href="#map" data-scroll>See on the map</a>
                    </div>
                </div>
                <div class="d-flex mb-4">
                    <i class="fe-mail h3 mb-2 text-light"></i>
                    <div class="pl-3">
                        <a class="d-inline-block text-light text-decoration-none mb-2" href="mailto:{{ settings.core.BusinessSettings.email }}">{{ settings.core.BusinessSettings.email }}</a>
                    </div>
                </div>
                <div class="d-flex mb-4">
                    <i class="fe-phone h3 mb-2 text-light"></i>
                    <div class="pl-3">
                        <a class="d-inline-block text-light text-decoration-none mb-2" href="tel:{{ settings.core.BusinessSettings.phone }}">{{ settings.core.BusinessSettings.phone }}</a>
                    </div>
                </div>
            </div>{% endcache %}
            <div class="col-xl-6 col-md-7">
                <div class="card border-0 box-shadow-lg">
                    <div class="card-body py-5 px-3 px-sm-4">
                        <h2 class="h3 text-center">{{ self.title }}</h2>
                        <p class="font-size-sm text-muted text-center">{{ self.subtitle }}</p>
                        <form class="needs-validation pt-2 px-md-3" novalidate method="POST" action="{% slugurl 'contact-us' %}">
                            {% csrf_token %} {% include 'partials/_alerts.html' %}
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_first_name">First name<sup class="text-danger ml-1">*</sup></label> {{ form.first_name }}
                                    <div class="invalid-feedback">Please enter your first name!</div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_last_name">Last name<sup class="text-danger ml-1">*</sup></label> {{ form.last_name }}
                                    <div class="invalid-feedback">Please enter your last name!</div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_email">Email address<sup class="text-danger ml-1">*</sup></label> {{ form.email }}
                                    <div class="invalid-feedback">Please enter a valid email address!</div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label class="form-label" for="id_phone_number">Phone number<sup class="text-danger ml-1">*</sup></label> {{ form.phone_number }}
                                    <div class="invalid-feedback">Please enter a valid phone number!</div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="id_message">Message<sup class="text-danger ml-1">*</sup></label> {{ form.message }}
                                <div class="invalid-feedback">Please write a message!</div>
                            </div>
                            <div class="text-center pt-2">
                                {{ form.captcha }}
                                <button class="btn btn-primary" type="submit">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="container py-5 py-md-6 py-lg-7" id="location">
        <div class="row py-sm-3">
            <div class="col-md-7">
                <div class="cs-gallery" id="map">{% image self.map_image fill-703x450 format-png as map_image %}
                    <a class="cs-gallery-item cs-map-popup bg-position-center bg-no-repeat py-7 text-center border rounded-lg" href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3145.0021611401357!2d-120.34119544822403!3d37.9770788796236!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8090c528b63b1ba3%3A0xb75939887ae2279d!2sRestore%20Orthopedics%20and%20Sports%20Medicine%3A%20Ariana%20DeMers%2C%20D.O.!5e0!3m2!1sen!2sus!4v1594873054045!5m2!1sen!2sus" data-iframe="true" data-sub-html="&lt;h6 class=&quot;font-size-sm text-light&quot;&gt;{{ settings.core.BusinessSettings.name }}&lt;/h6&gt;" style="background-image: url({{ map_image.url }});">
                        <span class="cs-gallery-caption"><i class="fe-maximize-2 font-size-xl mt-n1 mr-2"></i>Expand the map</span>
                        <div class="d-inline-block py-4 py-sm-7">
                            <img width="48" src="{% static 'img/svg/marker.svg' %}" alt="Map marker"/></div>
                    </a>
                </div>
            </div>{% cache 43200 contact_page_location %}
            <div class="col-md-4 offset-md-1 pt-4">
                <h2 class="h4 pb-3">Our Location</h2>
                <h3 class="h5">Address</h3>
                <ul class="list-unstyled font-size-sm mb-4 pb-2">
                    <li>{{ settings.core.BusinessSettings.street_address }}</li>
                    <li>{{ settings.core.BusinessSettings.city }}, {{ settings.core.BusinessSettings.state }} {{ settings.core.BusinessSettings.zip }}</li>
                </ul>
                <h2 class="h4 pb-2">Working hours</h2>
                <ul class="list-unstyled font-size-sm">
                    <li>
                        <span class="text-heading font-size-base mr-1">Sunday: </span><span class="text-danger">{{ settings.core.BusinessSettings.sunday_hours }}</span>
                    </li>
                    <li>
                        <span class="text-heading font-size-base mr-1">Monday: </span>{{ settings.core.BusinessSettings.monday_hours }}
                    </li>
                    <li>
                        <span class="text-heading font-size-base mr-1">Tuesday: </span>{{ settings.core.BusinessSettings.tuesday_hours }}
                    </li>
                    <li>
                        <span class="text-heading font-size-base mr-1">Wednesday: </span>{{ settings.core.BusinessSettings.wednesday_hours }}
                    </li>
                    <li>
                        <span class="text-heading font-size-base mr-1">Thursday: </span>{{ settings.core.BusinessSettings.thursday_hours }}
                    </li>
                    <li>
                        <span class="text-heading font-size-base mr-1">Friday: </span>{{ settings.core.BusinessSettings.friday_hours }}
                    </li>
                    <li>
                        <span class="text-heading font-size-base mr-1">Saturday: </span><span class="text-danger">{{ settings.core.BusinessSettings.saturday_hours }}</span>
                    </li>
                </ul>
            </div>{% endcache %}
        </div>
    </section>
{% endblock %}{% block extra_js %}
    <script src="{% static 'vendor/cleave.js/dist/cleave.min.js' %}"></script>
    <script src="{% static 'vendor/jarallax/dist/jarallax.min.js' %}"></script>
    <script src="{% static 'vendor/lightgallery.js/dist/js/lightgallery.min.js' %}"></script>{% endblock %}

templates/form-pages/form_field.html
<div class="col-md-4 form-group">
    {{ field.label_tag }}
    {{ field }}
    {% if field.help_text %}<small class="form-text text-muted">{{ field.help_text }}</small>{% endif %}
    {% if field.invalid_feedback %}<div class="invalid-feedback">{{ field.invalid_feedback }}</div>{% endif %}
    {% if field.valid_feedback %}<div class="valid-feedback">{{ field.valid_feedback }}</div>{% endif %}
</div>

templates/form-pages/test-form.html
{% extends 'base.html' %}{% load static wagtailcore_tags %}{% block extra_css %}<link rel="stylesheet" type="text/css" media="screen" href="{% static 'vendor/flatpickr/dist/flatpickr.min.css' %}">{% endblock %}
{% block content %}
    <div class="container">
    <h1>{{ page.title }}</h1>
    {{ page.intro|richtext }}
    <form action="{% pageurl page %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    </div>
{% endblock %}
{% block extra_js %}<script src="{% static 'vendor/flatpickr/dist/flatpickr.min.js' %}"></script>{% endblock %}